version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - sudo apt update -y
      - sudo apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

  pre_build:
    commands:
      - node --version
      - npm --version
      - npm ci --legacy-peer-deps

  build:
    commands:
      - git fetch origin master # Needed for git diff to work
      - git diff origin/master...HEAD --name-only
      - npx tsc --noEmit
      - npm run lint:changed
      - npm run format:changed
      - npm run prune
      - npm run build:prod
      - npm run build:ssr:prod

  post_build:
    commands:
      - npm run test
      - npm run cy:serve-and-run
    finally:
      - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
      - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
      - aws s3 cp $CODEBUILD_SRC_DIR/cypress s3://astrobin-ng-cypress-output/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: dist/frontend
