import { WatermarkPositionOptions, WatermarkSizeOptions } from "@shared/interfaces/image.interface";
import { LocationInterface } from "@shared/interfaces/location.interface";

export interface UserProfileInterface {
  id: number;
  deleted: Date;
  updated: Date;
  username: string;
  realName: string;
  website: string;
  job: string;
  hobbies: string;
  timezone: string;
  about: string;
  premiumOffer: string;
  premiumOfferExpiration: Date;
  premiumOfferSent: Date;
  companyName: string;
  companyDescription: string;
  companyWebsite: string;
  retailerCountry: string;
  avatar: string;
  excludeFromCompetition: boolean;
  defaultFrontPageSection: string;
  defaultGallerySorting: number;
  defaultLicense: number;
  defaultWatermarkText: string;
  defaultWatermark: boolean;
  defaultWatermarkSize: WatermarkSizeOptions;
  defaultWatermarkPosition: WatermarkPositionOptions;
  defaultWatermarkOpacity: number;
  acceptTos: boolean;
  openNotificationsInNewTab: boolean | null;
  receiveNewsletter: boolean;
  receiveImportantCommunications: boolean;
  receiveMarketingAndCommercialMaterial: boolean;
  allowAstronomyAds: boolean;
  allowRetailerIntegration: boolean;
  inactiveAccountReminderSent: Date;
  language: string;
  seenRealName: boolean;
  seenEmailPermissions: boolean;
  signature: string;
  signatureHtml: string;
  showSignatures: boolean;
  postCount: number;
  autoSubscribe: boolean;
  receiveForumEmails: boolean;
  user: number;
  telescopes: number[];
  mounts: number[];
  cameras: number[];
  focalReducers: number[];
  software: number[];
  filters: number[];
  accessories: number[];
  astroBinIndex?: number;
  contributionIndex?: number;
  followers?: number;
  premiumCounter: number;
  locations: LocationInterface[];
  email?: string;
}
