import { FeedItemInterface, FeedItemVerb } from "@features/home/interfaces/feed-item.interface";

export class FeedItemGenerator {
    static imageItem(): FeedItemInterface {
      return {
        "id": 258,
        "actorDisplayName": "asd",
        "actorUsername": "astrobin_dev",
        "actorAvatar": "https://dev-cdn.astrobin.com/images/avatars/8/e/2/resized/200/5513425551830a971d55e37bda23a521.png",
        "actorContentTypeName": "user",
        "targetUrl": null,
        "targetDisplayName": null,
        "targetUserUsername": null,
        "targetUserDisplayName": null,
        "targetUserAvatar": null,
        "actionObjectUrl": "/7pq17f/",
        "actionObjectDisplayName": "jojioi",
        "actionObjectUserUsername": "astrobin_dev2",
        "actionObjectUserDisplayName": "My name is really long, deal with it",
        "actionObjectUserAvatar": "https://dev-cdn.astrobin.com/images/avatars/c/b/3/resized/200/8e3757b1ade79e4fdeafef0484df313b.png",
        "image": "https://dev-cdn.astrobin.com/thumbs/eqAnI384TldM_1824x0_esdlMP5Y.jpg",
        "imageW": 1800,
        "imageH": 1960,
        "thumbnail": "https://dev-cdn.astrobin.com/thumbs/eqAnI384TldM_130x130_91BIk3MB.png",
        "othersCount": 0,
        "data": {
          "likeCount": 1,
          "bookmarkCount": 1,
          "commentCount": 0
        },
        "actorObjectId": "2",
        "verb": FeedItemVerb.VERB_BOOKMARKED_IMAGE,
        "description": null,
        "targetObjectId": null,
        "actionObjectObjectId": "227",
        "timestamp": "2024-12-18T10:02:24.062427",
        "public": true,
        "actorContentType": 58,
        "targetContentType": null,
        "actionObjectContentType": 132
      };
    }

    static revisionItem(): FeedItemInterface {
      return {
        "id": 217,
        "actorDisplayName": "asd",
        "actorUsername": "astrobin_dev",
        "actorAvatar": "https://dev-cdn.astrobin.com/images/avatars/8/e/2/resized/200/5513425551830a971d55e37bda23a521.png",
        "actorContentTypeName": "user",
        "targetUrl": "/87272c/G/",
        "targetDisplayName": "test iotd",
        "targetUserUsername": "astrobin_dev",
        "targetUserDisplayName": "asd",
        "targetUserAvatar": "https://dev-cdn.astrobin.com/images/avatars/8/e/2/resized/200/5513425551830a971d55e37bda23a521.png",
        "actionObjectUrl": "/87272c/G/",
        "actionObjectDisplayName": "test iotd (G)",
        "actionObjectUserUsername": "astrobin_dev",
        "actionObjectUserDisplayName": "asd",
        "actionObjectUserAvatar": "https://dev-cdn.astrobin.com/images/avatars/8/e/2/resized/200/5513425551830a971d55e37bda23a521.png",
        "image": "https://dev-cdn.astrobin.com/thumbs/zj20jJW0Lsjb_1824x0_esdlMP5Y.jpg",
        "imageW": 128,
        "imageH": 488,
        "thumbnail": "https://dev-cdn.astrobin.com/thumbs/zj20jJW0Lsjb_130x130_8GaQDu9P.png",
        "othersCount": null,
        "data": null,
        "actorObjectId": "2",
        "verb": FeedItemVerb.VERB_UPLOADED_REVISION,
        "description": null,
        "targetObjectId": "173",
        "actionObjectObjectId": "127",
        "timestamp": "2024-09-24T08:12:21.199681",
        "public": true,
        "actorContentType": 58,
        "targetContentType": 132,
        "actionObjectContentType": 135
      };
    }

    static marketplaceListingItem(): FeedItemInterface {
      return {
        "id": 28626264,
        "actorDisplayName": "Test",
        "actorUsername": "test",
        "actorAvatar": "https://cdn.astrobin.com/images/avatars/1/a/136706/resized/200/27396181cca5eabf1b77b66cc04a71ef.png",
        "actorContentTypeName": "user",
        "targetUrl": null,
        "targetDisplayName": null,
        "targetUserUsername": null,
        "targetUserDisplayName": null,
        "targetUserAvatar": null,
        "actionObjectUrl": "https://app.astrobin.com/equipment/marketplace/listing/l7uuhq",
        "actionObjectDisplayName": null,
        "actionObjectUserUsername": "test",
        "actionObjectUserDisplayName": "Test",
        "actionObjectUserAvatar": "https://cdn.astrobin.com/images/avatars/1/a/136706/resized/200/27396181cca5eabf1b77b66cc04a71ef.png",
        "image": "https://cdn.astrobin.com/marketplace-thumbs/136706/2024/b319cbf2-5305-4527-8923-6d73e4629ec3.jpg",
        "imageW": 512,
        "imageH": 849,
        "thumbnail": "https://cdn.astrobin.com/marketplace-thumbs/136706/2024/b319cbf2-5305-4527-8923-6d73e4629ec3.jpg",
        "othersCount": null,
        "data": null,
        "actorObjectId": "136706",
        "verb": FeedItemVerb.VERB_CREATED_MARKETPLACE_LISTING,
        "description": null,
        "targetObjectId": null,
        "actionObjectObjectId": "11255",
        "timestamp": "2024-12-19T20:12:53.242572",
        "public": true,
        "actorContentType": 3,
        "targetContentType": null,
        "actionObjectContentType": 1342
      };
    }

  static groupItem(): FeedItemInterface {
    return {
      "id": 28626264,
      "actorDisplayName": "Test",
      "actorUsername": "test",
      "actorAvatar": "https://cdn.astrobin.com/images/avatars/1/a/136706/resized/200/27396181cca5eabf1b77b66cc04a71ef.png",
      "actorContentTypeName": "user",
      "targetUrl": null,
      "targetDisplayName": null,
      "targetUserUsername": null,
      "targetUserDisplayName": null,
      "targetUserAvatar": null,
      "actionObjectUrl": "https://app.astrobin.com/equipment/marketplace/listing/l7uuhq",
      "actionObjectDisplayName": null,
      "actionObjectUserUsername": "test",
      "actionObjectUserDisplayName": "Test",
      "actionObjectUserAvatar": "https://cdn.astrobin.com/images/avatars/1/a/136706/resized/200/27396181cca5eabf1b77b66cc04a71ef.png",
      "image": "https://cdn.astrobin.com/marketplace-thumbs/136706/2024/b319cbf2-5305-4527-8923-6d73e4629ec3.jpg",
      "imageW": 512,
      "imageH": 849,
      "thumbnail": "https://cdn.astrobin.com/marketplace-thumbs/136706/2024/b319cbf2-5305-4527-8923-6d73e4629ec3.jpg",
      "othersCount": null,
      "data": null,
      "actorObjectId": "136706",
      "verb": FeedItemVerb.VERB_JOINED_GROUP,
      "description": null,
      "targetObjectId": null,
      "actionObjectObjectId": "11255",
      "timestamp": "2024-12-19T20:12:53.242572",
      "public": true,
      "actorContentType": 3,
      "targetContentType": null,
      "actionObjectContentType": 1342
    };
  }
}
